# Hexo Configuration/Hexo配置
## Docs/文档: https://hexo.io/docs/configuration.html
## Orignal Source/原项目地址: https://github.com/hexojs/hexo/
## My Source/该站点项目地址：https://github.com/JayMuShui/jaymushui.github.io


# Site/网站
title: MuYi Pavilion | 沐佚苑阁
subtitle: etude pour les petites dreamland.
description: ……楽しい旅をします あなたと一緒に、旅を
keywords:
 - JayMuShui
 - 沐
 - 木水
 - MuYi Pavilion
 - 沐佚苑阁
 - Blog
 - 博客
author: JayMuShui | 沐
language: 
- zh-CN
- zh-TW
- zh-HK
- en
- ja

timezone: Asia/Shanghai

# URL/网址
url: https://jaymushui.github.io
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true 
  trailing_html: true 

# Directory/目录
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
- README.md

# Writing/文章
new_post_name: :title.md 
default_layout: post
titlecase: false 
external_link:
  enable: true 
  field: site 
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting/主页面设置
index_generator:
# path: Root path for your blogs index page. (default = '') /懒
  path: ''
# per_page: Posts displayed per page. (0 = disable pagination)/懒
  per_page: 10
# order_by: Posts order. (Order by date descending by default)/懒
  order_by: -date

# Category & Tag/分类 & 标签
default_category: uncategorized
category_map:
tag_map:

# Metadata elements/元数据元素
##↑↑我不知道啊，老师（×）技术文档没教
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format / 日期时间格式
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination/分页
## per_page值为0时不分页
per_page: 10
pagination_dir: page

# Include / Exclude file(s) 
## 在 Hexo 配置文件中，通过设置 include/exclude 可以让 Hexo 进行处理或忽略某些目录和文件夹。可以使用glob表达式对目录和文件进行匹配。
include:
exclude:
ignore:

# Extensions/扩展
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: yun

#Display/播放器
aplayer:
  cdn: https://cdn.jsdelivr.net/npm/aplayer@latest/dist/APlayer.min.js
  style_cdn: https://cdn.jsdelivr.net/npm/aplayer@latest/dist/APlayer.min.css
  meting: true
  meting_cdn: https://cdn.jsdelivr.net/npm/meting@1/dist/Meting.min.js

# Deployment/部署
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: https://github.com/JayMuShui/jaymushui.github.io
  branch: master
  message: 修改歌单列表和一些小细节 # 你可以自定义此次部署更新的说明

