/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/links/friends_module': RouteRecordInfo<'/links/friends_module', '/links/friends_module', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/2022-08-21-Historical-Sketch-of-Guiping-No-1-Middle-School': RouteRecordInfo<'/posts/2022-08-21-Historical-Sketch-of-Guiping-No-1-Middle-School', '/posts/2022-08-21-Historical-Sketch-of-Guiping-No-1-Middle-School', Record<never, never>, Record<never, never>>,
    '/posts/2023-01-18-Personal-Reflections-on-The-Angel-Next-Door-Spoils-Me-Rotten': RouteRecordInfo<'/posts/2023-01-18-Personal-Reflections-on-The-Angel-Next-Door-Spoils-Me-Rotten', '/posts/2023-01-18-Personal-Reflections-on-The-Angel-Next-Door-Spoils-Me-Rotten', Record<never, never>, Record<never, never>>,
    '/posts/2023-11-07-Supernova-Era-Post-Reading-Reflections': RouteRecordInfo<'/posts/2023-11-07-Supernova-Era-Post-Reading-Reflections', '/posts/2023-11-07-Supernova-Era-Post-Reading-Reflections', Record<never, never>, Record<never, never>>,
    '/posts/2024-06-02-Etude-Pour-les-Petites-Supercordes': RouteRecordInfo<'/posts/2024-06-02-Etude-Pour-les-Petites-Supercordes', '/posts/2024-06-02-Etude-Pour-les-Petites-Supercordes', Record<never, never>, Record<never, never>>,
    '/posts/2024-10-26-Weak-Foundation-IT-Students-Tutorial-Installing-Visual-Studio-Code-Configuring-C-Cpp-Environment': RouteRecordInfo<'/posts/2024-10-26-Weak-Foundation-IT-Students-Tutorial-Installing-Visual-Studio-Code-Configuring-C-Cpp-Environment', '/posts/2024-10-26-Weak-Foundation-IT-Students-Tutorial-Installing-Visual-Studio-Code-Configuring-C-Cpp-Environment', Record<never, never>, Record<never, never>>,
    '/posts/2024-11-05-Simple-Encryption-and-Decryption-Algorithm-for-Tencent-QQ-Original-Stickers': RouteRecordInfo<'/posts/2024-11-05-Simple-Encryption-and-Decryption-Algorithm-for-Tencent-QQ-Original-Stickers', '/posts/2024-11-05-Simple-Encryption-and-Decryption-Algorithm-for-Tencent-QQ-Original-Stickers', Record<never, never>, Record<never, never>>,
    '/posts/2024-11-16-Question-of-TCS-CodeVita-Season-12-Round-1-Zone-1': RouteRecordInfo<'/posts/2024-11-16-Question-of-TCS-CodeVita-Season-12-Round-1-Zone-1', '/posts/2024-11-16-Question-of-TCS-CodeVita-Season-12-Round-1-Zone-1', Record<never, never>, Record<never, never>>,
    '/posts/2025-04-18-Wow-Another-Day-of-Doing-Nothing': RouteRecordInfo<'/posts/2025-04-18-Wow-Another-Day-of-Doing-Nothing', '/posts/2025-04-18-Wow-Another-Day-of-Doing-Nothing', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
